server:
  port: 10003

logging:
  level:
    com:
      example:
        demo: debug

eureka:
  instance:
    hostname: yanqun3
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://yanqun:10001/eureka,http://yanqun2:10002/eureka