server:
  port: 10010
spring:
  application:
    name: cloud-config-hi
  cloud:
    config:
      server:
        git:
          uri: https://github.com/automatous/cloud_config_rep.git
          default-label: master
  rabbitmq:
    host: 192.168.8.131

# 动态刷新配置 ---需要忽略权限拦截
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh